- name: Ensure apt-repo main pool path exist
  file:
    path: "{{ repo_path }}/pool/main"
    state: directory
    mode: '0755'
    recurse: true

- name: Copy peervpn deb package to apt-repo main pool
  copy:
    src: "{{ peervpn_build_path }}/deb/{{ peervpn_deb_package_name }}"
    dest: "{{ repo_path }}/pool/main/"
    owner: root
    mode: '0644'

- name: Ensure apt-repo binary-amd64 path exist
  file:
    path: "{{ repo_path }}/dists/stable/main/binary-amd64"
    state: directory
    mode: '0755'
    recurse: true

- name: Get peervpn debian scanpackages output
  command: 
    cmd: dpkg-scanpackages --arch amd64 pool/
    chdir: "{{ repo_path }}"
    register: dpkg_scanpackages_output

- name: Write peervpn debian scanpackages output to file
  copy: 
    content: "{{ dpkg_scanpackages_output }}"
    dest:  "{{ repo_path }}/dists/stable/main/binary-amd64/Packages"