- name: Ensure apt-repo main pool path exist
  file:
    path: "{{ repo_path }}/pool/main"
    state: directory
    mode: '0755'
    recurse: true

- name: Copy peervpn deb package to apt-repo main pool
  copy:
    src: "{{ peervpn_build_path }}/deb/{{ peervpn_deb_package_name }}"
    dest: "{{ repo_path }}/pool/main/"
    owner: root
    mode: '0644'

- name: Ensure apt-repo binary-amd64 path exist
  file:
    path: "{{ repo_path }}/dists/stable/main/binary-amd64"
    state: directory
    mode: '0755'
    recurse: true

#- name: Get peervpn debian scanpackages output
#  command: 
#    cmd: dpkg-scanpackages --arch amd64 pool/
#    chdir: "{{ repo_path }}"
#  register: dpkg_scanpackages_output

#- name: Write peervpn debian scanpackages output to file
#  copy: 
#    content: "{{ dpkg_scanpackages_output['stdout'] }}"
#    dest:  "{{ repo_path }}/dists/stable/main/binary-amd64/Packages"

- name: Get repo Packages file info
  command: 
    cmd: apt-ftparchive packages pool/main
    chdir: "{{ repo_path }}"
  register: "ftparchive_packages_output"

- name: Write repo Packages file info
  copy: 
    content: "{{ ftparchive_packages_output['stdout'] }}"
    dest:  "{{ repo_path }}/dists/stable/main/binary-amd64/Packages"

- name: Template an apt-repo release config
  template:
    src: apt.conf.j2
    dest: "{{ peervpn.build_path }}/apt.conf"
    owner: root
    mode: '0644'

- name: Get repo Release file info
  command: 
    cmd: "apt-ftparchive release -c={{ peervpn_build_path }}/apt.conf dists/stable"
    chdir: "{{ repo_path }}"
  register: "ftparchive_release_output"

- name: Write Get repo Release file info
  copy: 
    content: "{{ ftparchive_release_output['stdout'] }}"
    dest:  "{{ repo_path }}/dists/stable/main/binary-amd64/Release"


#- name: Create repo Release file
#  command: 
#    cmd: apt-ftparchive release dists/stable/main/binary-amd64/Release
#    chdir: "{{ repo_path }}"