- name: Ensure nginx is installed
  package:
    name: 
      - nginx
    state: present

- name: Template nginx config
  template:
    src: peervpn_nginx.conf.j2
    dest: "/etc/nginx/conf.d/peervpn_nginx.conf"
    owner: root
    mode: '0644'

- name: Restart nginx
  service: name=nginx state=restarted

