- name: Ensure nginx is installed
  package:
    name: 
      - nginx
    state: present

- name: Template nginx config
  template:
    src: peervpn_nginx.conf.j2
    dest: "/etc/nginx/conf.d/peervpn_nginx.conf"
    owner: root
    mode: '0644'

- name: Restart nginx
  service: name=nginx state=restarted

- name: Make hosts hack to route nginx hostname
  lineinfile:
    path: /etc/hosts
    regexp: "{{ repo_ip_addr }}"
    line: "{{ repo_ip_addr }} {{ repo_hostname }}"
    state: present

