- name: Install prerequisites
  import_tasks: prerequisites-installer.yaml

- name: Create local apt repo
  import_tasks: create-local-repo.yaml

- name: Deploy nginx with repo
  import_tasks: deploy-nginx.yaml