peervpn_git_repo_path: "https://github.com/peervpn/peervpn"
peervpn_git_dst_path: ""
peervpn_build_path: "/opt/build"
peervpn_deb_version: "0.0.1"
peervpn_deb_maintainer: "klimblinton"
peervpn_deb_depends: "libssl1.0-dev, libcrypto++-dev, zlib1g-dev"
      
