- name: Install prerequisites
  import_tasks: prerequisites-installer.yaml

- name: Ensure build path exist
  file:
    path: "{{ peervpn_build_path }}"
    state: directory
    mode: '0755'

- name: Clone peervpn source code
  git:
    repo: "{{ peervpn_git_repo_path }}"
    dest: "{{ peervpn_build_path }}/peervpn"
 
- name: Make binary
  import_tasks: make.yaml

- name: Create debian package
  import_tasks: dpkg_create.yaml

